theme: jekyll-theme-slate
remote_theme: # "manid2/lone-wolf-theme"
bootswatch_theme: "united" # cerulean, spacelab, united

# site Settings
lang: "en_US"
title: "MIT IAP Computational Law Course"
description: "The 2021 MIT Computational Law Course"
